### ISSUE TITLE
Issue uploading to Arduino nano 33

### ISSUE THREAD

**Issue by yunhaod** [leonardocavagnis/iOSArduinoBLE_ArduinoSketch#1]
<img width="363" alt="Screenshot 2024-01-23 225034" src="https://github.com/leonardocavagnis/iOSArduinoBLE_ArduinoSketch/assets/117396171/e978ecdb-4a0c-4411-8b04-d241e109d4e3">

Whenever I upload any code to the nano ble 33 board, it prints out a series of these = signs. I tried uploading a  non-ble code to an Arduino uno and it works perfectly and wouldn't yield what occurs in the picture. When I upload that same code to the nano33, it creates the image above. I believe the nano should have been able to process any that the uno can process? I have tried looking into others experiencing this issue but have no luck. 

Also, when I upload the bluetooth code into the nano, there is nothing being outputted in the serial monitor. I'm not quite sure on how to fix this issue.

**Comment by leonardocavagnis** [comment]
Hi @yunhaod,
Your issue is not directly related to this project. The appropriate platform to address questions like yours is https://forum.arduino.cc/.

Here's a tip: Add `while(!Serial) { }` after `Serial.begin(9600);` to wait for the serial port to open and observe output at startup.
